version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_userinfo_bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - LOG_CHANNEL_ID=${LOG_CHANNEL_ID}
      - ADMIN_ID=${ADMIN_ID}
    volumes:
      - .:/app
    restart: unless-stopped
